apiVersion: v1
kind: Intent
metadata:
  name: mixed-providers
  description: Example using both Helm and Terraform providers together

providers:
  helm:
    version: "1.0.0"
  terraform:
    version: "0.1.0"

components:
  # Infrastructure layer - Terraform
  - name: vpc-network
    type: terraform.network
    spec:
      module:
        source: "./infra/vpc"
      variables:
        environment: "production"
        cidr_block: "10.0.0.0/16"

  - name: eks-cluster
    type: terraform.cluster
    spec:
      module:
        source: "./infra/eks"
      variables:
        cluster_name: "production"
        cluster_version: "1.27"
    relationships:
      - target: vpc-network
        type: depends_on

  - name: payments-db
    type: terraform.database
    spec:
      module:
        source: "./infra/database"
      variables:
        name: "payments-db"
        engine: "postgres"
        size: "small"
    relationships:
      - target: vpc-network
        type: depends_on

  # Application layer - Helm
  - name: auth-service
    type: helm.service
    spec:
      chart:
        path: "./charts/auth-service"
      values:
        replicaCount: 2
        image:
          tag: "v1.2.3"
    relationships:
      - target: eks-cluster
        type: runs_on

  - name: payments-api
    type: helm.service
    spec:
      chart:
        path: "./charts/payments-api"
      values:
        replicaCount: 3
        database:
          host: "payments-db.example.com"
    relationships:
      - target: eks-cluster
        type: runs_on
      - target: payments-db
        type: connects_to

  - name: frontend
    type: helm.service
    spec:
      chart:
        repository: "https://charts.example.com"
        name: "frontend"
        version: "2.0.0"
      values:
        ingress:
          enabled: true
    relationships:
      - target: eks-cluster
        type: runs_on
      - target: auth-service
        type: connects_to
      - target: payments-api
        type: connects_to
