apiVersion: v1
kind: Intent
metadata:
  name: sourceplane-demo
  description: Demo application with mixed Helm and Terraform providers

providers:
  helm:
    version: "1.0.0"
  terraform:
    version: "0.1.0"

components:
  # Infrastructure Layer - Terraform
  - name: vpc-network
    type: terraform.network
    spec:
      module:
        source: "terraform-aws-modules/vpc/aws"
        version: "5.0.0"
      variables:
        name: "demo-vpc"
        cidr: "10.0.0.0/16"

  - name: eks-cluster
    type: terraform.cluster
    spec:
      module:
        source: "terraform-aws-modules/eks/aws"
        version: "19.0.0"
      variables:
        cluster_name: "demo-cluster"
        cluster_version: "1.27"
    relationships:
      - target: vpc-network
        type: depends_on

  - name: payments-db
    type: terraform.database
    spec:
      module:
        source: "terraform-aws-modules/rds/aws"
        version: "5.1.0"
      variables:
        identifier: "payments-db"
        engine: "postgres"
        engine_version: "14.5"
        instance_class: "db.t3.small"
    relationships:
      - target: vpc-network
        type: depends_on

  # Application Layer - Helm
  - name: auth-service
    type: helm.service
    spec:
      chart: bitnami/nginx
      version: "1.2.3"
      values:
        replicaCount: 2
    relationships:
      - target: eks-cluster
        type: runs_on

  - name: payments-api
    type: helm.service
    spec:
      chart: bitnami/nginx
      version: "1.2.3"
      values:
        replicaCount: 3
    relationships:
      - target: eks-cluster
        type: runs_on
      - target: payments-db
        type: connects_to

  - name: postgres-db
    type: helm.service
    spec:
      chart: bitnami/postgresql
      version: "11.0.0"
    relationships:
      - target: eks-cluster
        type: runs_on
