apiVersion: v1
kind: Intent
metadata:
  name: multi-tier-infrastructure
  description: Complete infrastructure stack with dependencies

providers:
  terraform:
    version: "0.1.0"
    defaults:
      backend:
        type: s3
        config:
          bucket: sourceplane-terraform-state
          region: us-east-1

components:
  # Layer 1: Foundation - Network Infrastructure
  - name: vpc-network
    type: terraform.network
    spec:
      path: terraform/vpc
      module:
        source: "terraform-aws-modules/vpc/aws"
        version: "5.0.0"
      variables:
        name: "demo-vpc"
        cidr: "10.0.0.0/16"
        azs: ["us-east-1a", "us-east-1b", "us-east-1c"]
        private_subnets: ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
        public_subnets: ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]
        enable_nat_gateway: true
        enable_dns_hostnames: true

  # Layer 2: Platform Services
  - name: eks-cluster
    type: terraform.cluster
    spec:
      path: terraform/eks
      module:
        source: "terraform-aws-modules/eks/aws"
        version: "19.0.0"
      variables:
        cluster_name: "demo-eks"
        cluster_version: "1.27"
        vpc_id: "${component.vpc-network.outputs.vpc_id}"
        subnet_ids: "${component.vpc-network.outputs.private_subnets}"
        enable_irsa: true
      relationships:
        - target: vpc-network
          type: depends_on

  - name: rds-database
    type: terraform.database
    spec:
      path: terraform/rds
      module:
        source: "terraform-aws-modules/rds/aws"
        version: "5.1.0"
      variables:
        identifier: "demo-postgres"
        engine: "postgres"
        engine_version: "14.7"
        instance_class: "db.t3.medium"
        allocated_storage: 100
        db_name: "application"
        username: "admin"
        vpc_security_group_ids: "${component.vpc-network.outputs.default_security_group_id}"
        db_subnet_group_name: "${component.vpc-network.outputs.database_subnet_group_name}"
      relationships:
        - target: vpc-network
          type: depends_on

  # Layer 3: Storage - Can run in parallel with platform
  - name: app-storage
    type: terraform.storage
    spec:
      path: terraform/s3
      resources:
        - type: aws_s3_bucket
          name: application_data
          config:
            bucket: "demo-app-data-${random_id.suffix.hex}"
            versioning:
              enabled: true
            server_side_encryption_configuration:
              rule:
                apply_server_side_encryption_by_default:
                  sse_algorithm: "AES256"

# Define explicit relationships for the dependency graph
relationships:
  - from: eks-cluster
    to: vpc-network
    type: depends_on
    
  - from: rds-database
    to: vpc-network
    type: depends_on
