apiVersion: v1
kind: Intent
metadata:
  name: aws-infrastructure
  description: Minimal Terraform example with AWS RDS database

providers:
  terraform:
    version: "0.1.0"

components:
  - name: payments-db
    type: terraform.database
    spec:
      module:
        source: "terraform-aws-modules/rds/aws"
        version: "5.1.0"
      variables:
        identifier: "payments-database"
        engine: "postgres"
        engine_version: "14.5"
        instance_class: "db.t3.small"
        allocated_storage: 50
