package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/sourceplane/cli/internal/parser"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize Sourceplane files",
	Long:  "Create initial blueprint or repository configurations",
}

var initBlueprintCmd = &cobra.Command{
	Use:   "blueprint",
	Short: "Initialize a new blueprint.yaml",
	RunE: func(cmd *cobra.Command, args []string) error {
		blueprintPath := "blueprint.yaml"

		// Check if file already exists
		if _, err := os.Stat(blueprintPath); err == nil {
			return fmt.Errorf("blueprint.yaml already exists")
		}

		// Create a sample blueprint
		blueprint := map[string]interface{}{
			"kind":       "Blueprint",
			"apiVersion": "sourceplane.io/v1",
			"provider":   "my-provider@v1",
			"repos": []map[string]interface{}{
				{
					"name": "example-api",
					"components": []map[string]interface{}{
						{
							"type": "service.api",
							"name": "api",
							"inputs": map[string]interface{}{
								"language": "go",
								"port":     8080,
							},
						},
					},
				},
			},
		}

		data, err := yaml.Marshal(blueprint)
		if err != nil {
			return fmt.Errorf("failed to create blueprint: %w", err)
		}

		if err := os.WriteFile(blueprintPath, data, 0644); err != nil {
			return fmt.Errorf("failed to write blueprint.yaml: %w", err)
		}

		fmt.Println("✅ Created blueprint.yaml")
		fmt.Println("\nNext steps:")
		fmt.Println("  1. Edit blueprint.yaml to define your repositories")
		fmt.Println("  2. Run 'sp plan' to preview changes")
		fmt.Println("  3. Run 'sp apply' to create repositories")

		return nil
	},
}

var planCmd = &cobra.Command{
	Use:   "plan",
	Short: "Preview what will be created from a blueprint",
	Long:  "Show repositories and components that will be created without making changes",
	RunE: func(cmd *cobra.Command, args []string) error {
		blueprintPath := "blueprint.yaml"

		blueprint, err := parser.LoadBlueprint(blueprintPath)
		if err != nil {
			return err
		}

		fmt.Println("📋 Blueprint Plan\n")
		fmt.Printf("Provider: %s\n\n", blueprint.Provider)

		if len(blueprint.Repos) == 0 {
			fmt.Println("No repositories defined")
			return nil
		}

		fmt.Printf("Will create %d repository(ies):\n\n", len(blueprint.Repos))

		for _, repo := range blueprint.Repos {
			fmt.Printf("📦 Repository: %s\n", repo.Name)
			if len(repo.Components) > 0 {
				fmt.Println("   Components:")
				for _, comp := range repo.Components {
					fmt.Printf("   ├─ %s [%s]\n", comp.Name, comp.Type)
					if len(comp.Inputs) > 0 {
						for key, value := range comp.Inputs {
							fmt.Printf("   │  • %s: %v\n", key, value)
						}
					}
				}
			} else {
				fmt.Println("   Components: (none)")
			}
			fmt.Println()
		}

		fmt.Println("⚠️  Run 'sp apply' to create these repositories")

		return nil
	},
}

var applyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Create repositories from a blueprint",
	Long:  "Generate repositories and components based on blueprint.yaml",
	RunE: func(cmd *cobra.Command, args []string) error {
		blueprintPath := "blueprint.yaml"

		blueprint, err := parser.LoadBlueprint(blueprintPath)
		if err != nil {
			return err
		}

		fmt.Println("🚀 Applying blueprint...\n")

		for _, repo := range blueprint.Repos {
			repoDir := repo.Name

			// Create directory
			if _, err := os.Stat(repoDir); os.IsNotExist(err) {
				if err := os.MkdirAll(repoDir, 0755); err != nil {
					return fmt.Errorf("failed to create directory %s: %w", repoDir, err)
				}
				fmt.Printf("✅ Created directory: %s\n", repoDir)
			} else {
				fmt.Printf("⚠️  Directory already exists: %s\n", repoDir)
				continue
			}

			// Create intent.yaml
			repoConfig := map[string]interface{}{
				"apiVersion": "sourceplane.io/v1",
				"kind":       "Repository",
				"metadata": map[string]interface{}{
					"name": repo.Name,
				},
				"provider":   blueprint.Provider,
				"components": repo.Components,
			}

			data, err := yaml.Marshal(repoConfig)
			if err != nil {
				return fmt.Errorf("failed to create intent.yaml for %s: %w", repo.Name, err)
			}

			intentYamlPath := filepath.Join(repoDir, "intent.yaml")
			if err := os.WriteFile(intentYamlPath, data, 0644); err != nil {
				return fmt.Errorf("failed to write intent.yaml: %w", err)
			}

			fmt.Printf("   ├─ Created intent.yaml\n")

			// Create README
			readmePath := filepath.Join(repoDir, "README.md")
			readmeContent := fmt.Sprintf("# %s\n\nGenerated by Sourceplane CLI\n\nProvider: %s\n", repo.Name, blueprint.Provider)
			if err := os.WriteFile(readmePath, []byte(readmeContent), 0644); err != nil {
				return fmt.Errorf("failed to write README.md: %w", err)
			}
			fmt.Printf("   └─ Created README.md\n\n")
		}

		fmt.Printf("✅ Successfully created %d repository(ies)\n", len(blueprint.Repos))
		fmt.Println("\nNext steps:")
		fmt.Println("  • Initialize Git repositories in each directory")
		fmt.Println("  • Review and commit the generated files")
		fmt.Println("  • Use providers to bootstrap component implementations")

		return nil
	},
}

func init() {
	initCmd.AddCommand(initBlueprintCmd)
	rootCmd.AddCommand(initCmd)
	rootCmd.AddCommand(planCmd)
	rootCmd.AddCommand(applyCmd)
}
